controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
error:
    path: /error
    controller: App\Controller\ErrorController
    methods: [POST, GET]

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

home:
    path: /
    controller: App\Controller\HomeController::index

profile:
    path: /profile
    controller: App\Controller\ProfileController::show
admin:
    path: /admin
    controller: App\Controller\AdminController::dashboard

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

app_register:
    path: /register
    controller: App\Controller\SecurityController::register
    
project_list:
    path: /projects
    controller: App\Controller\ProjectController::list
    
